steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/agentic-ai-mlg/orchestrator:latest'
      - '.'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/agentic-ai-mlg/orchestrator:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'orchestrator-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/agentic-ai-mlg/orchestrator:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'orchestrator-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=us-central1,ENVIRONMENT=production'
      - '--max-instances'
      - '10'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/agentic-ai-mlg/orchestrator:latest'

timeout: '1200s'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
